Balavardhan Reddy Kotla

700765621


1.Create a class Employee and then do the following:                                     



• Create a data member to count the number of Employees

• Create a constructor to initialize name, family, salary, department

• Create a function to average salary

• Create a Fulltime Employee class and it should inherit the properties of Employee class

• Create the instances of Fulltime Employee class and Employee class and call their member functions.

In [12]:
class Employee:
    employee_count = 0  # Data member to count the number of Employees

    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.employee_count += 1

    def average_salary(self, total_salary):
        return total_salary / Employee.employee_count

class FulltimeEmployee(Employee):
    # Inheriting properties from the Employee class
    pass

# Creating instances of Employee class
employee1 = Employee("Balavardhan", "Reddy", 100000, "Manager")
employee2 = Employee("Rajeshekar", "Konam", 90000, "IT")

# Creating instances of FulltimeEmployee class
fulltime_employee1 = FulltimeEmployee("Madhu", "Naidu", 75000, "Finance")
fulltime_employee2 = FulltimeEmployee("Keshav", "Shiva", 60000, "Marketing")

# Calling member functions
total_salary_employees = employee1.salary + employee2.salary
average_salary_employees = employee1.average_salary(total_salary_employees)

total_salary_fulltime_employees = fulltime_employee1.salary + fulltime_employee2.salary
average_salary_fulltime_employees = fulltime_employee1.average_salary(total_salary_fulltime_employees)

# Displaying results
print("Average Salary for Employees:", average_salary_employees)
print("Average Salary for Fulltime Employees:", average_salary_fulltime_employees)



Average Salary for Employees: 47500.0
Average Salary for Fulltime Employees: 33750.0


2.Numpy


Using NumPy create random vector of size 20 having only float in the range 1-20.

Then reshape the array to 4 by 5

Then replace the max in each row by 0 (axis=1)


In [13]:
# Import the NumPy library and alias it as 'np' for brevity and convention.
import numpy as np

# Create a random vector of size 20 with floats in the range 1-20
random_vector = np.random.uniform(1, 20, 20)

print("Original Random Vector:\n", random_vector)

Original Random Vector:
 [18.69556441 14.26241785  3.91360268  6.20547516 16.15153446  7.24800678
 10.80198082 10.01201219 12.34747453 18.66954418  8.42413274  9.20536204
 16.96346026 16.15292809  1.59798838  3.70058292 11.87997498 10.53542801
 11.13463086 17.85151064]


In [14]:
# Reshape the array to 4 by 5 (4 rows and 5 columns)
reshaped_array = random_vector.reshape(4, 5)

print(reshaped_array)

[[18.69556441 14.26241785  3.91360268  6.20547516 16.15153446]
 [ 7.24800678 10.80198082 10.01201219 12.34747453 18.66954418]
 [ 8.42413274  9.20536204 16.96346026 16.15292809  1.59798838]
 [ 3.70058292 11.87997498 10.53542801 11.13463086 17.85151064]]


In [15]:

# Replace the max in each row by 0 (axis=1)
reshaped_array[np.arange(4), reshaped_array.argmax(axis=1)] = 0

print("Reshaped Array:\n", reshaped_array)

Reshaped Array:
 [[ 0.         14.26241785  3.91360268  6.20547516 16.15153446]
 [ 7.24800678 10.80198082 10.01201219 12.34747453  0.        ]
 [ 8.42413274  9.20536204  0.         16.15292809  1.59798838]
 [ 3.70058292 11.87997498 10.53542801 11.13463086  0.        ]]
